static: run-snapd-from-snap: change back to uc18 like boot
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>

diff --git a/static/usr/lib/core/run-snapd-from-snap b/static/usr/lib/core/run-snapd-from-snap
--- a/static/usr/lib/core/run-snapd-from-snap
+++ b/static/usr/lib/core/run-snapd-from-snap
@@ -7,14 +7,26 @@ set -eux
 
 # run_on_unseeded will mount/run snapd on an unseeded system
 run_on_unseeded() {
-    SNAPD_BASE_DIR="/run/mnt/snapd"
+    SEED_SNAPD="$(find /var/lib/snapd/seed/snaps/ -name "snapd_*.snap")"
+    if [ ! -e "$SEED_SNAPD" ]; then
+        echo "Cannot find a seeded snapd"
+        ls /var/lib/snapd/seed/snaps
+        exit 1
+    fi
+
+    # mount snapd snap and run snapd directly, it will do
+    # the seeding and as part of this will restart snapd
+    # which will give it the right systemd unit.
+    TMPD=$(mktemp -d)
+    trap "umount $TMPD; rmdir $TMPD" EXIT
+    mount "$SEED_SNAPD" "$TMPD"
 
     # snapd will write all its needed snapd.{service,socket}
     # units and restart once it seeded the snapd snap. We create
     # a systemd socket unit so that systemd own the socket, otherwise
     # the socket file would be removed by snapd on exit and the snapd.seeded
     # service will fail because it has nothing to talk to anymore.
-    systemd-run --unit=snapd-seeding --service-type=notify --socket-property ListenStream=/run/snapd.socket --socket-property ListenStream=/run/snapd-snap.socket "$SNAPD_BASE_DIR"/usr/lib/snapd/snapd
+    systemd-run --unit=snapd-seeding --service-type=notify --socket-property ListenStream=/run/snapd.socket --socket-property ListenStream=/run/snapd-snap.socket "$TMPD"/usr/lib/snapd/snapd
     # we need to start the snapd service from above explicitly, systemd-run
     # only enables the socket but does not start the service.
     systemctl start --wait snapd-seeding.service
